In [1]:
import numpy as np
import math
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
plots.rcParams["patch.force_edgecolor"] = True

# Sample array of values
values = np.array([2.1, 3.31, 3.83, 3.11, 1.65, 1.73, 1.84, 2.49, 2.53, 2.99])  # Replace this with your actual array

# Compute the mean and standard deviation of the array
mean = np.mean(values)
std_dev = np.std(values)

# Generate a random sample of 100 values with a normal distribution
Aa_wing = np.random.normal(loc=mean, scale=std_dev, size=100)

print("Aa Wing:", Aa_wing)

Aa Wing: [ 4.73459016  2.69605786  2.07789092  1.4591788   2.32674442  3.34828944
  2.49971421  2.93029289  1.38061286  3.43504846  3.21986556  3.19507506
  4.29612087  2.33966306  2.54592626  3.1617718   2.95558033  3.32007894
  1.75213524  1.78883657  2.72778201  1.17033003  3.57655486  1.92727364
  1.87541662  2.6848525   2.5984356   2.49468785  2.50450027  1.33087486
  1.73778072  1.65886563  1.92126669  2.24136608  1.78679352  2.25878232
  2.51302532  2.47712641  2.88914666  2.82399295  3.03946268  2.63640134
  1.47369514  2.90466259  3.12318956  2.88412     2.36378646  1.99851474
  2.17168352  2.50717518  2.41309328  2.49357952  1.5901812   2.10313091
  3.24821748  3.9249832   1.89733391  3.53598135  1.87949631  1.91817865
  3.12124362  4.14582506  2.4304484   2.56176892  2.76316962  3.18325649
  2.57129274  3.61917143  2.89404725  2.44692186  4.5026645   3.23919326
  1.36645417  2.8322791   2.42658147  1.96141913  2.00797592  2.52423185
  2.51028501  3.71244802  1.81089439  2.79

In [15]:
Ant_L = Aa_wing*0.0970429+1.26276
Residuals= np.random.normal(loc=0, scale=.0582, size=100)
Ant=Ant_L+Residuals

In [16]:
Aa= Table().with_column("Aa Wing", Aa_wing).with_column("Aa Ant", Ant).show(100)
Aa

In [17]:
# Sample array of values
values = np.array([2.87, 4.02, 3.18, 3.51, 3.74, 3.95, 3.28])  # Replace this with your actual array

# Compute the mean and standard deviation of the array
mean = np.mean(values)
std_dev = np.std(values)

# Generate a random sample of 100 values with a normal distribution
Ax_Wing = np.random.normal(loc=mean, scale=std_dev, size=100)

print("Ax Wing:", Ax_Wing)

Ax Wing: [ 3.31538271  3.74478554  3.1753866   3.99775682  4.03919722  3.62833969
  3.93213984  3.28223639  2.43271468  3.24143112  3.74120582  4.23306885
  3.74911941  3.00338851  2.67906624  4.300372    3.70181639  3.21156477
  3.40673161  3.67136909  2.79983914  3.65369077  3.37887107  3.65850562
  2.78008673  3.44997091  3.91357008  3.72475542  4.09887477  4.10473337
  3.23902935  3.8634223   3.35424418  3.6693059   2.97997207  3.48715117
  4.22577546  3.16488255  3.47516714  4.14811156  3.53852123  3.65569718
  3.27886509  2.38843584  2.93260613  3.18720003  3.51704404  3.68975954
  3.65877627  3.86124619  3.78605093  3.53644321  4.15095434  3.83368891
  3.16671821  3.26342291  3.14893395  3.64396889  3.91306241  3.27619691
  3.54400955  3.73603821  3.48525037  3.20413665  4.28562772  3.10119845
  3.56541199  2.82911119  3.69764791  4.02877718  3.75575041  3.5231035
  3.75164536  3.52773652  3.75484049  3.54435493  3.21395396  2.75355383
  3.63078412  3.47531866  2.99128816  3.474

In [18]:
Ax_Ant_L = 0.105147*Ax_Wing + 0.908376
Ax_Ant_L

array([ 1.25697855,  1.30212896,  1.24225837,  1.32872814,  1.33308547,
        1.28988503,  1.32182871,  1.25349331,  1.16416865,  1.24920276,
        1.30175257,  1.35347049,  1.30258466,  1.22417329,  1.19007178,
        1.36054721,  1.29761089,  1.2460624 ,  1.26658361,  1.29440945,
        1.20277069,  1.29255062,  1.26365416,  1.29305689,  1.20069378,
        1.27113009,  1.31987615,  1.30002286,  1.33936039,  1.3399764 ,
        1.24895022,  1.31460326,  1.26106471,  1.29419251,  1.22171112,
        1.27503948,  1.35270361,  1.24115391,  1.2737794 ,  1.34453749,
        1.28044089,  1.29276159,  1.25313883,  1.15951286,  1.21673074,
        1.24350052,  1.27818263,  1.29634315,  1.29308535,  1.31437445,
        1.3064679 ,  1.28022239,  1.3448364 ,  1.31147689,  1.24134692,
        1.25151513,  1.23947696,  1.2915284 ,  1.31982277,  1.25285828,
        1.28101797,  1.30120921,  1.27483962,  1.24528136,  1.3589969 ,
        1.23445771,  1.28326837,  1.20584855,  1.29717258,  1.33

In [19]:
Residuals = np.random.normal(loc=0, scale=0.049, size=100)
Residuals

array([-0.03733219,  0.05143631,  0.00025661,  0.00565447, -0.08067272,
        0.019419  ,  0.00466994,  0.00886493, -0.03198763,  0.04859885,
        0.00656614,  0.04445495,  0.02358526,  0.00057587, -0.03221509,
        0.05288435, -0.05173456, -0.05038544, -0.0581367 , -0.04412071,
        0.05288153,  0.03926331, -0.00770835,  0.00283915,  0.05653493,
        0.01794189,  0.00575527,  0.02832789,  0.01395982, -0.00468778,
        0.13250375, -0.11478856, -0.01508264,  0.0246405 , -0.0597925 ,
       -0.0036182 , -0.03286794, -0.08960815,  0.03809021,  0.0095036 ,
        0.07414817, -0.02027379, -0.04319459, -0.05305787,  0.01360649,
        0.03197341, -0.03124553, -0.00143849,  0.06948188,  0.08855907,
       -0.02926457,  0.02748808,  0.09748923,  0.07156374, -0.02882347,
        0.05105646,  0.03760229,  0.08085233, -0.02994048, -0.07972095,
       -0.04859956,  0.0863831 , -0.04729259, -0.01252782, -0.04638604,
       -0.04400778, -0.04084592, -0.01791873, -0.01574877,  0.05

In [20]:
Ax_Ant= Ax_Ant_L+Residuals
Ax_Ant

array([ 1.21964636,  1.35356528,  1.24251498,  1.33438261,  1.25241275,
        1.30930404,  1.32649865,  1.26235824,  1.13218102,  1.29780161,
        1.30831871,  1.39792544,  1.32616992,  1.22474916,  1.15785668,
        1.41343157,  1.24587633,  1.19567696,  1.20844691,  1.25028874,
        1.25565222,  1.33181393,  1.25594581,  1.29589604,  1.25722871,
        1.28907198,  1.32563142,  1.32835074,  1.35332021,  1.33528862,
        1.38145396,  1.19981471,  1.24598207,  1.31883301,  1.16191862,
        1.27142129,  1.31983568,  1.15154576,  1.3118696 ,  1.35404109,
        1.35458906,  1.2724878 ,  1.20994424,  1.106455  ,  1.23033722,
        1.27547393,  1.2469371 ,  1.29490465,  1.36256723,  1.40293353,
        1.27720332,  1.30771047,  1.44232562,  1.38304063,  1.21252345,
        1.30257159,  1.27707925,  1.37238073,  1.28988229,  1.17313732,
        1.23241841,  1.38759231,  1.22754703,  1.23275354,  1.31261086,
        1.19044993,  1.24242245,  1.18792982,  1.28142382,  1.38

In [21]:
good_Ax_table=Table().with_column('Ax Wing', Ax_Wing).with_column('Ax Ant', Ax_Ant).show(100)
good_Ax_table